# Generated by Django 5.2.7 on 2025-10-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(help_text='Price in cents'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(help_text='Price in cents'),
        ),
    ]
